<?php

use App\Models\Rubric;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('rubrics', function (Blueprint $table) {
            $table->id();
            $table->string('title',100);
            $table->string('title_r',100)->nullable();
            $table->tinyText('description')->nullable();
            //$table->unsignedBigInteger('parent_id')->nullable();
            //$table->foreign('parent_id')->references('id')->on('rubrics')->onDelete('restrict');
            $table->unsignedBigInteger('sort')->default(500);
            $table->nestedSet();
            $table->unsignedBigInteger('level')->nullable();
            $table->timestamps();
        });
        //Rubric::create(['title' => 'Продажа','level' => 0]);
        //Rubric::create(['title' => 'Аренда','level' => 0]);
        $id_0 = Rubric::create(['id'=>0,'title' => 'Аренда','level' => 0]);
        $id_1 = Rubric::create(['id'=>1,'title' => 'Дорожно-строительная техника','title_r' => 'дорожно-строительной техники','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_2 = Rubric::create(['id'=>2,'title' => 'Кран','title_r' => 'крана','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_3 = Rubric::create(['id'=>3,'title' => 'Погрузчик','title_r' => 'погрузчика','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_4 = Rubric::create(['id'=>4,'title' => 'Подъемник','title_r' => 'подъемника','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_5 = Rubric::create(['id'=>5,'title' => 'Самосвал','title_r' => 'самосвала','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_6 = Rubric::create(['id'=>6,'title' => 'Техника для бетона','title_r' => 'техники для бетона','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_7 = Rubric::create(['id'=>7,'title' => 'Транспортировка','title_r' => 'техники транспортировки','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_8 = Rubric::create(['id'=>8,'title' => 'Экскаватор','title_r' => 'экскаватора','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_9 = Rubric::create(['id'=>9,'title' => 'Другое','title_r' => '','parent_id' => $id_0->id,'sort'=> 999,'level' => 1]);
        $id_10 = Rubric::create(['id'=>10,'title' => 'Бетонозавод','title_r' => 'бетонозавода','parent_id' => $id_6->id,'sort'=> 100,'level' => 2]);
        $id_11 = Rubric::create(['id'=>11,'title' => 'Бетононасос','title_r' => 'бетононасоса','parent_id' => $id_6->id,'sort'=> 100,'level' => 2]);
        $id_12 = Rubric::create(['id'=>12,'title' => 'Бетононасос стационарный','title_r' => 'бетононасоса стационарного','parent_id' => $id_6->id,'sort'=> 100,'level' => 2]);
        $id_13 = Rubric::create(['id'=>13,'title' => 'Бетоносмеситель','title_r' => 'бетоносмесителя','parent_id' => $id_6->id,'sort'=> 100,'level' => 2]);
        $id_14 = Rubric::create(['id'=>14,'title' => 'Бетоносмеситель полуприцеп','title_r' => 'бетоносмесителя полуприцепа','parent_id' => $id_6->id,'sort'=> 100,'level' => 2]);
        $id_15 = Rubric::create(['id'=>15,'title' => 'Бетоноукладчик','title_r' => 'бетоноукладчика','parent_id' => $id_6->id,'sort'=> 100,'level' => 2]);
        $id_16 = Rubric::create(['id'=>16,'title' => 'Другое','title_r' => '','parent_id' => $id_6->id,'sort'=> 999,'level' => 2]);
        $id_17 = Rubric::create(['id'=>17,'title' => 'Автовышка','title_r' => 'автовышки','parent_id' => $id_4->id,'sort'=> 100,'level' => 2]);
        $id_18 = Rubric::create(['id'=>18,'title' => 'Подъемник коленчатый','title_r' => 'подъемника коленчатого','parent_id' => $id_4->id,'sort'=> 100,'level' => 2]);
        $id_19 = Rubric::create(['id'=>19,'title' => 'Подъемник мачтовый','title_r' => 'подъемника мачтового','parent_id' => $id_4->id,'sort'=> 100,'level' => 2]);
        $id_20 = Rubric::create(['id'=>20,'title' => 'Подъемник ножничный','title_r' => 'подъемника ножничного','parent_id' => $id_4->id,'sort'=> 100,'level' => 2]);
        $id_21 = Rubric::create(['id'=>21,'title' => 'Подъемник телескопический','title_r' => 'подъемника телескопического','parent_id' => $id_4->id,'sort'=> 100,'level' => 2]);
        $id_22 = Rubric::create(['id'=>22,'title' => 'Подъемник фасадный','title_r' => 'подъемника фасадного','parent_id' => $id_4->id,'sort'=> 100,'level' => 2]);
        $id_23 = Rubric::create(['id'=>23,'title' => 'Другое','title_r' => '','parent_id' => $id_4->id,'sort'=> 999,'level' => 2]);
        $id_24 = Rubric::create(['id'=>24,'title' => 'Автогудронатор','title_r' => 'автогудронатора','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_25 = Rubric::create(['id'=>25,'title' => 'Асфальтный завод','title_r' => 'асфальтного завода','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_26 = Rubric::create(['id'=>26,'title' => 'Асфальтоукладчик гусеничный','title_r' => 'гусеничного асфальтаукладчика','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_27 = Rubric::create(['id'=>27,'title' => 'Асфальтоукладчик колесный','title_r' => 'колесного асфальтаукладчика','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_28 = Rubric::create(['id'=>28,'title' => 'Бульдозер','title_r' => 'бульдозера','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_29 = Rubric::create(['id'=>29,'title' => 'Виброплита','title_r' => 'виброплиты','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_30 = Rubric::create(['id'=>30,'title' => 'Грейдер','title_r' => 'грейдера','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_31 = Rubric::create(['id'=>31,'title' => 'Дорожная фреза','title_r' => 'дорожной фрезы','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_32 = Rubric::create(['id'=>32,'title' => 'Дорожный каток','title_r' => 'дорожного катка','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_33 = Rubric::create(['id'=>33,'title' => 'Каток грунтовый','title_r' => 'грунтового катка','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_34 = Rubric::create(['id'=>34,'title' => 'Каток прицепной','title_r' => 'прицепного катка','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_35 = Rubric::create(['id'=>35,'title' => 'Каток тротуарный','title_r' => 'тротуарного катка','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_36 = Rubric::create(['id'=>36,'title' => 'Компактор','title_r' => 'компактора','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_37 = Rubric::create(['id'=>37,'title' => 'Машина для укладки тротуарной плитки','title_r' => 'машины для укладки тротуарной плитки','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_38 = Rubric::create(['id'=>38,'title' => 'Пневмоколесный каток','title_r' => 'пневмоколесоного катка','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_39 = Rubric::create(['id'=>39,'title' => 'Разметочная машина','title_r' => 'разметочной машины','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_40 = Rubric::create(['id'=>40,'title' => 'Резчик швов','title_r' => 'резчика швов','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_41 = Rubric::create(['id'=>41,'title' => 'Ресайклер','title_r' => 'ресайклера','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_42 = Rubric::create(['id'=>42,'title' => 'Скрепер','title_r' => 'скрепера','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_43 = Rubric::create(['id'=>43,'title' => 'Трамбовщик','title_r' => 'трамбовщика','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_44 = Rubric::create(['id'=>44,'title' => 'Другое','title_r' => '','parent_id' => $id_1->id,'sort'=> 999,'level' => 2]);
        $id_45 = Rubric::create(['id'=>45,'title' => 'Автокран','title_r' => 'автокрана','parent_id' => $id_2->id,'sort'=> 100,'level' => 2]);
        $id_46 = Rubric::create(['id'=>46,'title' => 'Башенный кран','title_r' => 'башенного крана','parent_id' => $id_2->id,'sort'=> 100,'level' => 2]);
        $id_47 = Rubric::create(['id'=>47,'title' => 'Гусеничный кран','title_r' => 'гусенечного крана','parent_id' => $id_2->id,'sort'=> 100,'level' => 2]);
        $id_48 = Rubric::create(['id'=>48,'title' => 'Козловой кран','title_r' => 'козлового крана','parent_id' => $id_2->id,'sort'=> 100,'level' => 2]);
        $id_49 = Rubric::create(['id'=>49,'title' => 'Мини кран','title_r' => 'мини-крана','parent_id' => $id_2->id,'sort'=> 100,'level' => 2]);
        $id_50 = Rubric::create(['id'=>50,'title' => 'Другое','title_r' => '','parent_id' => $id_2->id,'sort'=> 999,'level' => 2]);
        $id_51 = Rubric::create(['id'=>51,'title' => 'Минипогрузчик','title_r' => 'минипогрузчика','parent_id' => $id_3->id,'sort'=> 100,'level' => 2]);
        $id_52 = Rubric::create(['id'=>52,'title' => 'Минипогрузчик гусеничный','title_r' => 'гусеничного минипогрузчика','parent_id' => $id_3->id,'sort'=> 100,'level' => 2]);
        $id_53 = Rubric::create(['id'=>53,'title' => 'Погрузчик гусеничный','title_r' => 'гусеничного погрузчика','parent_id' => $id_3->id,'sort'=> 100,'level' => 2]);
        $id_54 = Rubric::create(['id'=>54,'title' => 'Погрузчик телескопический','title_r' => 'телескопического погрузчика','parent_id' => $id_3->id,'sort'=> 100,'level' => 2]);
        $id_55 = Rubric::create(['id'=>55,'title' => 'Фронтальный погрузчик','title_r' => 'фронтального погрузчика','parent_id' => $id_3->id,'sort'=> 100,'level' => 2]);
        $id_56 = Rubric::create(['id'=>56,'title' => 'Другое','title_r' => '','parent_id' => $id_3->id,'sort'=> 999,'level' => 2]);
        $id_57 = Rubric::create(['id'=>57,'title' => 'Гусеничный самосвал','title_r' => 'гусеничного самосвала','parent_id' => $id_5->id,'sort'=> 100,'level' => 2]);
        $id_58 = Rubric::create(['id'=>58,'title' => 'Карьерный самосвал','title_r' => 'карьерного самосвала','parent_id' => $id_5->id,'sort'=> 100,'level' => 2]);
        $id_59 = Rubric::create(['id'=>59,'title' => 'Мини-самосвал','title_r' => 'мини-самосвала','parent_id' => $id_5->id,'sort'=> 100,'level' => 2]);
        $id_60 = Rubric::create(['id'=>60,'title' => 'Самосвал','title_r' => 'самосвала','parent_id' => $id_5->id,'sort'=> 100,'level' => 2]);
        $id_61 = Rubric::create(['id'=>61,'title' => 'Шарнирный самосвал','title_r' => 'шарнирного самосвала','parent_id' => $id_5->id,'sort'=> 100,'level' => 2]);
        $id_62 = Rubric::create(['id'=>62,'title' => 'Другое','title_r' => '','parent_id' => $id_5->id,'sort'=> 999,'level' => 2]);
        $id_63 = Rubric::create(['id'=>63,'title' => 'Полуприцеп низкорамная платформа','title_r' => 'низкорамной платформы-полуприцепа','parent_id' => $id_7->id,'sort'=> 100,'level' => 2]);
        $id_64 = Rubric::create(['id'=>64,'title' => 'Портовый тягач','title_r' => 'портового тягача','parent_id' => $id_7->id,'sort'=> 100,'level' => 2]);
        $id_65 = Rubric::create(['id'=>65,'title' => 'Прицеп низкорамная платформа','title_r' => 'низкорамной платформы-прицепа','parent_id' => $id_7->id,'sort'=> 100,'level' => 2]);
        $id_66 = Rubric::create(['id'=>66,'title' => 'Специальный тягач','title_r' => 'специального тягача','parent_id' => $id_7->id,'sort'=> 100,'level' => 2]);
        $id_67 = Rubric::create(['id'=>67,'title' => 'Другое','title_r' => '','parent_id' => $id_7->id,'sort'=> 999,'level' => 2]);
        $id_68 = Rubric::create(['id'=>68,'title' => 'Гусеничный экскаватор','title_r' => 'гусеничного экскаватора','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_69 = Rubric::create(['id'=>69,'title' => 'Драглайн','title_r' => 'драглайна','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_70 = Rubric::create(['id'=>70,'title' => 'Земснаряд','title_r' => 'земснаряда','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_71 = Rubric::create(['id'=>71,'title' => 'Колесный экскаватор','title_r' => 'колесного экскаватора','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_72 = Rubric::create(['id'=>72,'title' => 'Мини-экскаватор','title_r' => 'мини-экскаватора','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_73 = Rubric::create(['id'=>73,'title' => 'Многоковшовый экскаватор','title_r' => 'многоковшового экскаватора','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_74 = Rubric::create(['id'=>74,'title' => 'Траншеекопатель','title_r' => 'траншеекопателя','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_75 = Rubric::create(['id'=>75,'title' => 'Шагающий экскаватор','title_r' => 'шагающего экскаватора','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_76 = Rubric::create(['id'=>76,'title' => 'Экскаватор для перевалки','title_r' => 'экскаватора для перевалки','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_77 = Rubric::create(['id'=>77,'title' => 'Экскаватор для разрушения','title_r' => 'экскаватора для разрушения','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_78 = Rubric::create(['id'=>78,'title' => 'Экскаватор на рельсовом ходу','title_r' => 'экскаватора на рельсовом ходу','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_79 = Rubric::create(['id'=>79,'title' => 'Экскаватор-планировщик','title_r' => 'экскаватора-планировщика','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_80 = Rubric::create(['id'=>80,'title' => 'Экскаватор-погрузчик','title_r' => 'экскаватора-погрузчика','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_81 = Rubric::create(['id'=>81,'title' => 'Экскаватор с прямой лопатой','title_r' => 'экскаватора с прямой лопатой','parent_id' => $id_8->id,'sort'=> 100,'level' => 2]);
        $id_82 = Rubric::create(['id'=>82,'title' => 'Другое','title_r' => '','parent_id' => $id_8->id,'sort'=> 999,'level' => 2]);
        $id_83 = Rubric::create(['id'=>83,'title' => 'Другое','title_r' => '','parent_id' => $id_9->id,'sort'=> 999,'level' => 2]);
        $id_84 = Rubric::create(['id'=>84,'title' => 'Вилочный погрузчик','title_r' => 'вилочного погрузчика','parent_id' => $id_3->id,'sort'=> 100,'level' => 2]);
        $id_85 = Rubric::create(['id'=>85,'title' => 'Инструмент','title_r' => 'инструмента','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_86 = Rubric::create(['id'=>86,'title' => 'Ручной инструмент','title_r' => 'ручного инструмента','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_87 = Rubric::create(['id'=>87,'title' => 'Тепловые пушки','title_r' => 'тепловых пушек','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_88 = Rubric::create(['id'=>88,'title' => 'Электрогенераторы','title_r' => 'электрогенератора','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_89 = Rubric::create(['id'=>89,'title' => 'Дизельный электрогенератор','title_r' => 'дизельного электрогенератора','parent_id' => $id_88->id,'sort'=> 100,'level' => 2]);
        $id_93 = Rubric::create(['id'=>93,'title' => 'Штроборез','title_r' => 'штробореза','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_92 = Rubric::create(['id'=>92,'title' => 'Мотобур','title_r' => 'мотобура','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_94 = Rubric::create(['id'=>94,'title' => 'Рубанок','title_r' => 'рубанка','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_95 = Rubric::create(['id'=>95,'title' => 'Вибратор','title_r' => 'вибратора','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_96 = Rubric::create(['id'=>96,'title' => 'Мусоропровод','title_r' => 'мусоропровода','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_97 = Rubric::create(['id'=>97,'title' => 'Паркетошлифовальная машина','title_r' => 'паркетошлифовальной машины','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_98 = Rubric::create(['id'=>98,'title' => 'Пылесос строительный','title_r' => 'пылесоса строительного','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_99 = Rubric::create(['id'=>99,'title' => 'Захват бордюрный','title_r' => 'захвата бордюрного','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_100 = Rubric::create(['id'=>100,'title' => 'Пила','title_r' => 'пилы','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_101 = Rubric::create(['id'=>101,'title' => 'Шуруповёрт','title_r' => 'шуруповёрта','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_102 = Rubric::create(['id'=>102,'title' => 'Шлифмашинка','title_r' => 'шлифмашинки','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_103 = Rubric::create(['id'=>103,'title' => 'Тепловентилятор','title_r' => 'тепловентилятора','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_104 = Rubric::create(['id'=>104,'title' => 'Затирочная машина ','title_r' => 'затирочной машины','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_105 = Rubric::create(['id'=>105,'title' => 'Мойка высокого давления','title_r' => 'мойки высокого давления','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_106 = Rubric::create(['id'=>106,'title' => 'Лестница','title_r' => 'лестиницы','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_107 = Rubric::create(['id'=>107,'title' => 'Перфоратор','title_r' => 'перфоратора','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_108 = Rubric::create(['id'=>108,'title' => 'Отвал','title_r' => 'отвала','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_110 = Rubric::create(['id'=>110,'title' => 'Бензиновый генератор','title_r' => 'бензинового генератора','parent_id' => $id_88->id,'sort'=> 100,'level' => 2]);
        $id_111 = Rubric::create(['id'=>111,'title' => 'Бензорез','title_r' => 'бензореза','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_112 = Rubric::create(['id'=>112,'title' => 'Илосос','title_r' => 'илососа','parent_id' => $id_1->id,'sort'=> 100,'level' => 2]);
        $id_113 = Rubric::create(['id'=>113,'title' => 'Консольный кран','title_r' => 'консольного крана','parent_id' => $id_2->id,'sort'=> 100,'level' => 2]);
        $id_114 = Rubric::create(['id'=>114,'title' => 'Сварочный инструмент','title_r' => 'сварочного инструмента','parent_id' => $id_85->id,'sort'=> 100,'level' => 2]);
        $id_115 = Rubric::create(['id'=>115,'title' => 'Гидроманипулятор','title_r' => 'гидроманипулятора','parent_id' => $id_7->id,'sort'=> 100,'level' => 2]);
        $id_117 = Rubric::create(['id'=>117,'title' => 'Электротранспорт','title_r' => 'электротранспорта','parent_id' => $id_0->id,'sort'=> 100,'level' => 1]);
        $id_118 = Rubric::create(['id'=>118,'title' => 'Грузовые трициклы','title_r' => 'грузового трицикла','parent_id' => $id_117->id,'sort'=> 100,'level' => 2]);
        $id_119 = Rubric::create(['id'=>119,'title' => 'Складкая техника','title_r' => 'складской техники','parent_id' => $id_117->id,'sort'=> 100,'level' => 2]);
        $id_120 = Rubric::create(['id'=>120,'title' => 'Строительная техника','title_r' => 'строительной техники','parent_id' => $id_117->id,'sort'=> 100,'level' => 2]);
        $idp_0 = Rubric::create(['id'=>0,'title' => 'Продажа','level' => 0]);
        $idp_1 = Rubric::create(['id'=>1,'title' => 'Дорожно-строительная техника','title_r' => 'дорожно-строительной техники','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_2 = Rubric::create(['id'=>2,'title' => 'Кран','title_r' => 'крана','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_3 = Rubric::create(['id'=>3,'title' => 'Погрузчик','title_r' => 'погрузчика','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_4 = Rubric::create(['id'=>4,'title' => 'Подъемник','title_r' => 'подъемника','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_5 = Rubric::create(['id'=>5,'title' => 'Самосвал','title_r' => 'самосвала','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_6 = Rubric::create(['id'=>6,'title' => 'Техника для бетона','title_r' => 'техники для бетона','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_7 = Rubric::create(['id'=>7,'title' => 'Транспортировка','title_r' => 'техники транспортировки','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_8 = Rubric::create(['id'=>8,'title' => 'Экскаватор','title_r' => 'экскаватора','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_9 = Rubric::create(['id'=>9,'title' => 'Другое','title_r' => '','parent_id' => $idp_0->id,'sort'=> 999,'level' => 1]);
        $idp_10 = Rubric::create(['id'=>10,'title' => 'Бетонозавод','title_r' => 'бетонозавода','parent_id' => $idp_6->id,'sort'=> 100,'level' => 2]);
        $idp_11 = Rubric::create(['id'=>11,'title' => 'Бетононасос','title_r' => 'бетононасоса','parent_id' => $idp_6->id,'sort'=> 100,'level' => 2]);
        $idp_12 = Rubric::create(['id'=>12,'title' => 'Бетононасос стационарный','title_r' => 'бетононасоса стационарного','parent_id' => $idp_6->id,'sort'=> 100,'level' => 2]);
        $idp_13 = Rubric::create(['id'=>13,'title' => 'Бетоносмеситель','title_r' => 'бетоносмесителя','parent_id' => $idp_6->id,'sort'=> 100,'level' => 2]);
        $idp_14 = Rubric::create(['id'=>14,'title' => 'Бетоносмеситель полуприцеп','title_r' => 'бетоносмесителя полуприцепа','parent_id' => $idp_6->id,'sort'=> 100,'level' => 2]);
        $idp_15 = Rubric::create(['id'=>15,'title' => 'Бетоноукладчик','title_r' => 'бетоноукладчика','parent_id' => $idp_6->id,'sort'=> 100,'level' => 2]);
        $idp_16 = Rubric::create(['id'=>16,'title' => 'Другое','title_r' => '','parent_id' => $idp_6->id,'sort'=> 999,'level' => 2]);
        $idp_17 = Rubric::create(['id'=>17,'title' => 'Автовышка','title_r' => 'автовышки','parent_id' => $idp_4->id,'sort'=> 100,'level' => 2]);
        $idp_18 = Rubric::create(['id'=>18,'title' => 'Подъемник коленчатый','title_r' => 'подъемника коленчатого','parent_id' => $idp_4->id,'sort'=> 100,'level' => 2]);
        $idp_19 = Rubric::create(['id'=>19,'title' => 'Подъемник мачтовый','title_r' => 'подъемника мачтового','parent_id' => $idp_4->id,'sort'=> 100,'level' => 2]);
        $idp_20 = Rubric::create(['id'=>20,'title' => 'Подъемник ножничный','title_r' => 'подъемника ножничного','parent_id' => $idp_4->id,'sort'=> 100,'level' => 2]);
        $idp_21 = Rubric::create(['id'=>21,'title' => 'Подъемник телескопический','title_r' => 'подъемника телескопического','parent_id' => $idp_4->id,'sort'=> 100,'level' => 2]);
        $idp_22 = Rubric::create(['id'=>22,'title' => 'Подъемник фасадный','title_r' => 'подъемника фасадного','parent_id' => $idp_4->id,'sort'=> 100,'level' => 2]);
        $idp_23 = Rubric::create(['id'=>23,'title' => 'Другое','title_r' => '','parent_id' => $idp_4->id,'sort'=> 999,'level' => 2]);
        $idp_24 = Rubric::create(['id'=>24,'title' => 'Автогудронатор','title_r' => 'автогудронатора','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_25 = Rubric::create(['id'=>25,'title' => 'Асфальтный завод','title_r' => 'асфальтного завода','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_26 = Rubric::create(['id'=>26,'title' => 'Асфальтоукладчик гусеничный','title_r' => 'гусеничного асфальтаукладчика','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_27 = Rubric::create(['id'=>27,'title' => 'Асфальтоукладчик колесный','title_r' => 'колесного асфальтаукладчика','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_28 = Rubric::create(['id'=>28,'title' => 'Бульдозер','title_r' => 'бульдозера','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_29 = Rubric::create(['id'=>29,'title' => 'Виброплита','title_r' => 'виброплиты','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_30 = Rubric::create(['id'=>30,'title' => 'Грейдер','title_r' => 'грейдера','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_31 = Rubric::create(['id'=>31,'title' => 'Дорожная фреза','title_r' => 'дорожной фрезы','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_32 = Rubric::create(['id'=>32,'title' => 'Дорожный каток','title_r' => 'дорожного катка','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_33 = Rubric::create(['id'=>33,'title' => 'Каток грунтовый','title_r' => 'грунтового катка','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_34 = Rubric::create(['id'=>34,'title' => 'Каток прицепной','title_r' => 'прицепного катка','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_35 = Rubric::create(['id'=>35,'title' => 'Каток тротуарный','title_r' => 'тротуарного катка','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_36 = Rubric::create(['id'=>36,'title' => 'Компактор','title_r' => 'компактора','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_37 = Rubric::create(['id'=>37,'title' => 'Машина для укладки тротуарной плитки','title_r' => 'машины для укладки тротуарной плитки','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_38 = Rubric::create(['id'=>38,'title' => 'Пневмоколесный каток','title_r' => 'пневмоколесоного катка','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_39 = Rubric::create(['id'=>39,'title' => 'Разметочная машина','title_r' => 'разметочной машины','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_40 = Rubric::create(['id'=>40,'title' => 'Резчик швов','title_r' => 'резчика швов','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_41 = Rubric::create(['id'=>41,'title' => 'Ресайклер','title_r' => 'ресайклера','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_42 = Rubric::create(['id'=>42,'title' => 'Скрепер','title_r' => 'скрепера','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_43 = Rubric::create(['id'=>43,'title' => 'Трамбовщик','title_r' => 'трамбовщика','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_44 = Rubric::create(['id'=>44,'title' => 'Другое','title_r' => '','parent_id' => $idp_1->id,'sort'=> 999,'level' => 2]);
        $idp_45 = Rubric::create(['id'=>45,'title' => 'Автокран','title_r' => 'автокрана','parent_id' => $idp_2->id,'sort'=> 100,'level' => 2]);
        $idp_46 = Rubric::create(['id'=>46,'title' => 'Башенный кран','title_r' => 'башенного крана','parent_id' => $idp_2->id,'sort'=> 100,'level' => 2]);
        $idp_47 = Rubric::create(['id'=>47,'title' => 'Гусеничный кран','title_r' => 'гусенечного крана','parent_id' => $idp_2->id,'sort'=> 100,'level' => 2]);
        $idp_48 = Rubric::create(['id'=>48,'title' => 'Козловой кран','title_r' => 'козлового крана','parent_id' => $idp_2->id,'sort'=> 100,'level' => 2]);
        $idp_49 = Rubric::create(['id'=>49,'title' => 'Мини кран','title_r' => 'мини-крана','parent_id' => $idp_2->id,'sort'=> 100,'level' => 2]);
        $idp_50 = Rubric::create(['id'=>50,'title' => 'Другое','title_r' => '','parent_id' => $idp_2->id,'sort'=> 999,'level' => 2]);
        $idp_51 = Rubric::create(['id'=>51,'title' => 'Минипогрузчик','title_r' => 'минипогрузчика','parent_id' => $idp_3->id,'sort'=> 100,'level' => 2]);
        $idp_52 = Rubric::create(['id'=>52,'title' => 'Минипогрузчик гусеничный','title_r' => 'гусеничного минипогрузчика','parent_id' => $idp_3->id,'sort'=> 100,'level' => 2]);
        $idp_53 = Rubric::create(['id'=>53,'title' => 'Погрузчик гусеничный','title_r' => 'гусеничного погрузчика','parent_id' => $idp_3->id,'sort'=> 100,'level' => 2]);
        $idp_54 = Rubric::create(['id'=>54,'title' => 'Погрузчик телескопический','title_r' => 'телескопического погрузчика','parent_id' => $idp_3->id,'sort'=> 100,'level' => 2]);
        $idp_55 = Rubric::create(['id'=>55,'title' => 'Фронтальный погрузчик','title_r' => 'фронтального погрузчика','parent_id' => $idp_3->id,'sort'=> 100,'level' => 2]);
        $idp_56 = Rubric::create(['id'=>56,'title' => 'Другое','title_r' => '','parent_id' => $idp_3->id,'sort'=> 999,'level' => 2]);
        $idp_57 = Rubric::create(['id'=>57,'title' => 'Гусеничный самосвал','title_r' => 'гусеничного самосвала','parent_id' => $idp_5->id,'sort'=> 100,'level' => 2]);
        $idp_58 = Rubric::create(['id'=>58,'title' => 'Карьерный самосвал','title_r' => 'карьерного самосвала','parent_id' => $idp_5->id,'sort'=> 100,'level' => 2]);
        $idp_59 = Rubric::create(['id'=>59,'title' => 'Мини-самосвал','title_r' => 'мини-самосвала','parent_id' => $idp_5->id,'sort'=> 100,'level' => 2]);
        $idp_60 = Rubric::create(['id'=>60,'title' => 'Самосвал','title_r' => 'самосвала','parent_id' => $idp_5->id,'sort'=> 100,'level' => 2]);
        $idp_61 = Rubric::create(['id'=>61,'title' => 'Шарнирный самосвал','title_r' => 'шарнирного самосвала','parent_id' => $idp_5->id,'sort'=> 100,'level' => 2]);
        $idp_62 = Rubric::create(['id'=>62,'title' => 'Другое','title_r' => '','parent_id' => $idp_5->id,'sort'=> 999,'level' => 2]);
        $idp_63 = Rubric::create(['id'=>63,'title' => 'Полуприцеп низкорамная платформа','title_r' => 'низкорамной платформы-полуприцепа','parent_id' => $idp_7->id,'sort'=> 100,'level' => 2]);
        $idp_64 = Rubric::create(['id'=>64,'title' => 'Портовый тягач','title_r' => 'портового тягача','parent_id' => $idp_7->id,'sort'=> 100,'level' => 2]);
        $idp_65 = Rubric::create(['id'=>65,'title' => 'Прицеп низкорамная платформа','title_r' => 'низкорамной платформы-прицепа','parent_id' => $idp_7->id,'sort'=> 100,'level' => 2]);
        $idp_66 = Rubric::create(['id'=>66,'title' => 'Специальный тягач','title_r' => 'специального тягача','parent_id' => $idp_7->id,'sort'=> 100,'level' => 2]);
        $idp_67 = Rubric::create(['id'=>67,'title' => 'Другое','title_r' => '','parent_id' => $idp_7->id,'sort'=> 999,'level' => 2]);
        $idp_68 = Rubric::create(['id'=>68,'title' => 'Гусеничный экскаватор','title_r' => 'гусеничного экскаватора','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_69 = Rubric::create(['id'=>69,'title' => 'Драглайн','title_r' => 'драглайна','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_70 = Rubric::create(['id'=>70,'title' => 'Земснаряд','title_r' => 'земснаряда','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_71 = Rubric::create(['id'=>71,'title' => 'Колесный экскаватор','title_r' => 'колесного экскаватора','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_72 = Rubric::create(['id'=>72,'title' => 'Мини-экскаватор','title_r' => 'мини-экскаватора','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_73 = Rubric::create(['id'=>73,'title' => 'Многоковшовый экскаватор','title_r' => 'многоковшового экскаватора','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_74 = Rubric::create(['id'=>74,'title' => 'Траншеекопатель','title_r' => 'траншеекопателя','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_75 = Rubric::create(['id'=>75,'title' => 'Шагающий экскаватор','title_r' => 'шагающего экскаватора','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_76 = Rubric::create(['id'=>76,'title' => 'Экскаватор для перевалки','title_r' => 'экскаватора для перевалки','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_77 = Rubric::create(['id'=>77,'title' => 'Экскаватор для разрушения','title_r' => 'экскаватора для разрушения','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_78 = Rubric::create(['id'=>78,'title' => 'Экскаватор на рельсовом ходу','title_r' => 'экскаватора на рельсовом ходу','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_79 = Rubric::create(['id'=>79,'title' => 'Экскаватор-планировщик','title_r' => 'экскаватора-планировщика','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_80 = Rubric::create(['id'=>80,'title' => 'Экскаватор-погрузчик','title_r' => 'экскаватора-погрузчика','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_81 = Rubric::create(['id'=>81,'title' => 'Экскаватор с прямой лопатой','title_r' => 'экскаватора с прямой лопатой','parent_id' => $idp_8->id,'sort'=> 100,'level' => 2]);
        $idp_82 = Rubric::create(['id'=>82,'title' => 'Другое','title_r' => '','parent_id' => $idp_8->id,'sort'=> 999,'level' => 2]);
        $idp_83 = Rubric::create(['id'=>83,'title' => 'Другое','title_r' => '','parent_id' => $idp_9->id,'sort'=> 999,'level' => 2]);
        $idp_84 = Rubric::create(['id'=>84,'title' => 'Вилочный погрузчик','title_r' => 'вилочного погрузчика','parent_id' => $idp_3->id,'sort'=> 100,'level' => 2]);
        $idp_85 = Rubric::create(['id'=>85,'title' => 'Инструмент','title_r' => 'инструмента','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_86 = Rubric::create(['id'=>86,'title' => 'Ручной инструмент','title_r' => 'ручного инструмента','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_87 = Rubric::create(['id'=>87,'title' => 'Тепловые пушки','title_r' => 'тепловых пушек','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_88 = Rubric::create(['id'=>88,'title' => 'Электрогенераторы','title_r' => 'электрогенератора','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_89 = Rubric::create(['id'=>89,'title' => 'Дизельный электрогенератор','title_r' => 'дизельного электрогенератора','parent_id' => $idp_88->id,'sort'=> 100,'level' => 2]);
        $idp_93 = Rubric::create(['id'=>93,'title' => 'Штроборез','title_r' => 'штробореза','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_92 = Rubric::create(['id'=>92,'title' => 'Мотобур','title_r' => 'мотобура','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_94 = Rubric::create(['id'=>94,'title' => 'Рубанок','title_r' => 'рубанка','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_95 = Rubric::create(['id'=>95,'title' => 'Вибратор','title_r' => 'вибратора','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_96 = Rubric::create(['id'=>96,'title' => 'Мусоропровод','title_r' => 'мусоропровода','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_97 = Rubric::create(['id'=>97,'title' => 'Паркетошлифовальная машина','title_r' => 'паркетошлифовальной машины','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_98 = Rubric::create(['id'=>98,'title' => 'Пылесос строительный','title_r' => 'пылесоса строительного','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_99 = Rubric::create(['id'=>99,'title' => 'Захват бордюрный','title_r' => 'захвата бордюрного','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_100 = Rubric::create(['id'=>100,'title' => 'Пила','title_r' => 'пилы','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_101 = Rubric::create(['id'=>101,'title' => 'Шуруповёрт','title_r' => 'шуруповёрта','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_102 = Rubric::create(['id'=>102,'title' => 'Шлифмашинка','title_r' => 'шлифмашинки','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_103 = Rubric::create(['id'=>103,'title' => 'Тепловентилятор','title_r' => 'тепловентилятора','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_104 = Rubric::create(['id'=>104,'title' => 'Затирочная машина ','title_r' => 'затирочной машины','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_105 = Rubric::create(['id'=>105,'title' => 'Мойка высокого давления','title_r' => 'мойки высокого давления','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_106 = Rubric::create(['id'=>106,'title' => 'Лестница','title_r' => 'лестиницы','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_107 = Rubric::create(['id'=>107,'title' => 'Перфоратор','title_r' => 'перфоратора','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_108 = Rubric::create(['id'=>108,'title' => 'Отвал','title_r' => 'отвала','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_110 = Rubric::create(['id'=>110,'title' => 'Бензиновый генератор','title_r' => 'бензинового генератора','parent_id' => $idp_88->id,'sort'=> 100,'level' => 2]);
        $idp_111 = Rubric::create(['id'=>111,'title' => 'Бензорез','title_r' => 'бензореза','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_112 = Rubric::create(['id'=>112,'title' => 'Илосос','title_r' => 'илососа','parent_id' => $idp_1->id,'sort'=> 100,'level' => 2]);
        $idp_113 = Rubric::create(['id'=>113,'title' => 'Консольный кран','title_r' => 'консольного крана','parent_id' => $idp_2->id,'sort'=> 100,'level' => 2]);
        $idp_114 = Rubric::create(['id'=>114,'title' => 'Сварочный инструмент','title_r' => 'сварочного инструмента','parent_id' => $idp_85->id,'sort'=> 100,'level' => 2]);
        $idp_115 = Rubric::create(['id'=>115,'title' => 'Гидроманипулятор','title_r' => 'гидроманипулятора','parent_id' => $idp_7->id,'sort'=> 100,'level' => 2]);
        $idp_117 = Rubric::create(['id'=>117,'title' => 'Электротранспорт','title_r' => 'электротранспорта','parent_id' => $idp_0->id,'sort'=> 100,'level' => 1]);
        $idp_118 = Rubric::create(['id'=>118,'title' => 'Грузовые трициклы','title_r' => 'грузового трицикла','parent_id' => $idp_117->id,'sort'=> 100,'level' => 2]);
        $idp_119 = Rubric::create(['id'=>119,'title' => 'Складкая техника','title_r' => 'складской техники','parent_id' => $idp_117->id,'sort'=> 100,'level' => 2]);
        $idp_120 = Rubric::create(['id'=>120,'title' => 'Строительная техника','title_r' => 'строительной техники','parent_id' => $idp_117->id,'sort'=> 100,'level' => 2]);



    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('rubrics');
    }
};
